# Generated by Django 5.0.4 on 2024-10-28 21:37

import account.validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[account.validator.validate_phone_number],
                verbose_name="Phone number",
            ),
        ),
    ]
